Add guard for when ``name`` is ``None``
FerrisChat/Server pull request #21
Opened 2021-08-31 02:12 UTC by jay3332

Pray that I got it correct because I need to sleep

2021-08-31 02:21 UTC, tazz4843 requested changes
For examples of what I mean, check out [`ferrischat_webserver/src/users/edit_user.rs`](https://github.com/FerrisChat/Server/blob/develop/ferrischat_webserver/src/users/edit_user.rs)

2021-08-31 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/guilds/edit_guild.rs
> +            let db = get_db_or_fail!();
Move this back to the root of the function that way you only fetch it once.

2021-08-31 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/guilds/edit_guild.rs
>      .await;
There's no point in fetching this until all of the updates are done.

2021-08-31 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/guilds/edit_guild.rs
> +                "UPDATE guilds SET name = $1 WHERE id = $2 RETURNING *",
Don't have it return anything. Like I said on Discord, do a separate query to fetch the object after everything is done.

2021-08-31 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/guilds/edit_guild.rs
> +        None => HttpResponse::BadRequest().finish()
This shouldn't be a 400, the field is Option for a reason.

2021-08-31 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/guilds/edit_guild.rs
> +                        members: None,
Do another query to fetch the updated guild object after you've done the query to update it.

2021-09-03 20:07 UTC, Drxckzyz commented
wow this needs alot of Work

2021-09-04 17:20 UTC, closed without merging

2021-09-04 17:20 UTC, hydrostaticcog commented
Stale