Add full author data to messages
FerrisChat/Server pull request #43
Opened 2021-11-12 02:19 UTC by jay3332

2021-11-12 02:21 UTC, tazz4843 requested changes
someone is going to need to `cargo check` this

2021-11-12 02:21 UTC, tazz4843 commented on ferrischat_webserver/src/messages/send_message.rs
> +    let author = match sql::query!("SELECT * FROM users WHERE id = $1", bigint_author_id)
sqlx

2021-11-12 02:24 UTC, hydrostaticcog commented
Just as a general rule of thumb, you should at the very minimum `cargo check` and `cargo fmt` any PR. It's be even better if you actually built and tested though.

2021-11-12 02:39 UTC, tazz4843 approved these changes
i'll be damned 
![kuva](https://user-images.githubusercontent.com/60516372/141399558-3eed738f-8b27-4e95-b489-4814bda39556.png)

2021-11-12 02:40 UTC, merged

2021-11-12 02:57 UTC, hydrostaticcog commented on ferrischat_webserver/src/messages/get_messages.rs
> +                let author = match sql::query!("SELECT * FROM users WHERE id = $1", m.author_id)
`sqlx::query` not sql

2021-11-13 03:33 UTC, hydrostaticcog commented
This needs to be reverted ASAP