Update message_history.rs
FerrisChat/Server pull request #44
Opened 2021-11-13 03:22 UTC by Cryptex-github

2021-11-13 03:25 UTC, tazz4843 commented on ferrischat_webserver/src/messages/message_history.rs
> +    let oldest_first = params.oldest_first;
Just unpack the struct here instead.
```rs
let GetMessageHistoryParams { mut limit, oldest_first } = params;
```

2021-11-13 03:26 UTC, jay3332 commented on ferrischat_webserver/src/messages/message_history.rs
> +            ) AS author FROM messages m WHERE channel_id = $1 ORDER BY id AESC LIMIT $2"#;
should be ``ASC`` not ``AESC``

2021-11-13 03:26 UTC, jay3332 commented on ferrischat_webserver/src/messages/message_history.rs
> +            ) AS author FROM messages m WHERE channel_id = $1 ORDER BY id AESC LIMIT $2"#
should be ``ASC`` not ``AESC``

2021-11-13 05:09 UTC, hydrostaticcog requested changes

2021-11-13 05:09 UTC, hydrostaticcog commented on ferrischat_webserver/src/messages/message_history.rs
> +        let resp = sqlx::query!(query, bigint_channel_id, limit)
`sqlx::query` expects a string literal; will fail to compile.

2021-11-14 00:03 UTC, tazz4843 approved these changes

2021-11-14 00:04 UTC, merged